### ISSUE TITLE
UMAD_DEV_DIR replaced by RDMA_CDEV_DIR

### ISSUE THREAD

**Issue by jarodwilson** [linux-rdma/ibsim#10]
When using the latest rdma-core, parts of ibsim fail to build:

 + git clone https://github.com/linux-rdma/ibsim
    Cloning into 'ibsim'...
    + cd ibsim
    + make
    make -C ibsim all &&   make -C umad2sim all &&   make -C tests all &&  echo "Done."
    make[1]: Entering directory '/var/str/ibsim/ibsim'
    cc -Wall -g -fpic -I. -I../include -I/usr/include -c -o sim_net.o sim_net.c
    cc -Wall -g -fpic -I. -I../include -I/usr/include -c -o sim_mad.o sim_mad.c
    cc -Wall -g -fpic -I. -I../include -I/usr/include -c -o sim_cmd.o sim_cmd.c
    cc -Wall -g -fpic -I. -I../include -I/usr/include -c -o ibsim.o ibsim.c
    cc -fpic -o ibsim sim_net.o sim_mad.o sim_cmd.o ibsim.o -L/usr/lib64 -libmad -libumad
    make[1]: Leaving directory '/var/str/ibsim/ibsim'
    make[1]: Entering directory '/var/str/ibsim/umad2sim'
    cc -Wall -g -fpic -I. -I../include -I/usr/include -c -o umad2sim.o umad2sim.c
    umad2sim.c:112:30: error: UMAD_DEV_DIR undeclared here (not in a function); did you mean MAD_DEST?
     static char umad_dev_dir[] = UMAD_DEV_DIR;

Relevant rdma-core commit can be seen here:

https://github.com/linux-rdma/rdma-core/commit/69c3e4cbbcc7fe3f9831945c66debb7fa546f87b#diff-0962153bc328f14508d7a2033494c6ab

**Comment by Honggang-LI** [comment]
https://github.com/linux-rdma/ibsim/commit/7bf171bab9c8bf3cc6c8f822bfcbd85570ca9abc

It can be closed as resolved, as this commit fixes this issue.

**Comment by tamirronen** [comment]
issue resolved by the following commit
https://github.com/linux-rdma/ibsim/pull/11/commits/7bf171bab9c8bf3cc6c8f822bfcbd85570ca9abc
